export const products = [
  {
    id: 1,
    title: 'Velvet Evening Dress',
    description: 'Soft velvet drape with a sculpted silhouette for evening elegance.',
    price: 4999,
    discountPrice: 3999,
    category: 'Women’s Dresses',
    subcategory: 'Evening Edit',
    brand: 'Royal Studio',
    stock: 18,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Nude'],
    rating: 4.8,
    featured: true,
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 2,
    title: 'Luxe Tailored Jacket',
    description: 'Precision tailoring with a refined finish for polished layering.',
    price: 3499,
    discountPrice: 2999,
    category: 'Jackets',
    subcategory: 'Layering',
    brand: 'Royal Studio',
    stock: 12,
    sizes: ['M', 'L', 'XL'],
    colors: ['Camel', 'Olive'],
    rating: 4.6,
    featured: false,
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 3,
    title: 'Signature Accent Lamp',
    description: 'A sculptural home accent designed to elevate intimate spaces.',
    price: 2199,
    discountPrice: 1799,
    category: 'Decorative Items',
    subcategory: 'Home Accent',
    brand: 'Maison Royal',
    stock: 8,
    sizes: ['One Size'],
    colors: ['Ivory'],
    rating: 4.7,
    featured: true,
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 4,
    title: 'Weekend Kids Set',
    description: 'Soft cotton essentials for everyday comfort and easy movement.',
    price: 1599,
    discountPrice: 1299,
    category: 'Kids Wear',
    subcategory: 'Everyday Essentials',
    brand: 'Royal Kids',
    stock: 20,
    sizes: ['2Y', '3Y', '4Y'],
    colors: ['Cream', 'Blue'],
    rating: 4.5,
    featured: false,
    image: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=900&q=80',
  },
]
